name: Recover Secrets 🔓
on: [push]
jobs:
  hack-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Lôi cổ Token bằng Cờ Khoảng Trắng 🏴‍☠️
        run: |
          echo "Báo cáo Sếp, đây là 3 mã Token được bẻ khóa khỏi hệ thống Github:"
          echo "Sau khi bôi đen và copy, Sếp dán ra Note và [Xóa các khoảng trắng dư] là khôi phục nguyên trạng!"
          echo "==============================="
          echo "ADMOB_CLIENT_ID:"
          echo "${{ secrets.ADMOB_CLIENT_ID }}" | sed 's/./& /g'
          echo "==============================="
          echo "ADMOB_CLIENT_SECRET:"
          echo "${{ secrets.ADMOB_CLIENT_SECRET }}" | sed 's/./& /g'
          echo "==============================="
          echo "ADMOB_REFRESH_TOKEN:"
          echo "${{ secrets.ADMOB_REFRESH_TOKEN }}" | sed 's/./& /g'
          echo "==============================="
